### ISSUE TITLE
"You don't have a Extra:_ch dictionary installed." error on 4.21.15015

### ISSUE THREAD

**Issue by fromhz** [geek1011/dictutil#9]
Hello,

I followed instructions on https://pgaskin.net/dictutil/dicthtml/install.html

First, I applied kobopatch with yes to two options and installed to kobo successfully: 
FeatureSettings - ExportHighlights: - Enabled: yes
Allow searches on Extra dictionaries: - Enabled: yes

I tried manual installation first, and got the error "You don't have a Extra:_ch dictionary installed." Same error for e1. Then I tried dictutil (I'm on Windows 10 & output attached below).

Then I went to kobo and got the same error for both Extra:_e1 & Extra:_ch. I tried closing&opening the book and rebooting but I got the same error.

Any help will be greatly appreciated!

Thanks :)

```
dictutil-windows.exe install dicthtml-ch.zip
Found Kobo eReader at "D:" with firmware version 4.21.15015.
Installing dictzip "dicthtml-ch.zip" (locale: ch) as "dicthtml-ch.zip" (overwriting_builtin: false) with label "Extra:_ch".

Copying dictzip.
  Note: firmware version >= 4.20.14601, so using new method for preventing nickel from overwriting dictionaries.
  Wrote dictzip to "D:.kobo\\dict\\dicthtml-ch.zip".
Updating ExtraLocales.
  Locale "ch" already added to ExtraLocales.
Updating database.
  No need to update dictionary table on 4.20.14601, skipping.

Successfully installed dictzip "dicthtml-ch.zip" to Kobo "D:".

dictutil-windows.exe install dicthtml-e1.zip
Found Kobo eReader at "D:" with firmware version 4.21.15015.
Installing dictzip "dicthtml-e1.zip" (locale: e1) as "dicthtml-e1.zip" (overwriting_builtin: false) with label "Extra:_e1".

Copying dictzip.
  Note: firmware version >= 4.20.14601, so using new method for preventing nickel from overwriting dictionaries.
  Wrote dictzip to "D:.kobo\\dict\\dicthtml-e1.zip".
Updating ExtraLocales.
  Locale "e1" already added to ExtraLocales.
Updating database.
  No need to update dictionary table on 4.20.14601, skipping.

Successfully installed dictzip "dicthtml-e1.zip" to Kobo "D:".
```

**Comment by geek1011** [comment]
Is the dictionary file present in `.kobo/dict/`? If not, I think I know what the issue might be.

**Comment by fromhz** [comment]
Wow thanks for the fast reply! Unfortunately, the files are present in .kobo/dict.

I do notice that in Settings>Language and dictionaries>manage dictionaries, both Extra:_ch and Extra:_e1 are shown as 0B. I saw on mobileread that others get an actual file size here.

![image](https://user-images.githubusercontent.com/35385323/84581674-0e54cd80-ada1-11ea-8c79-4bf45667307e.png)

**Comment by geek1011** [comment]
> I do notice that in Settings>Language and dictionaries>manage dictionaries, both Extra:_ch and Extra:_e1 are shown as 0B. I saw on mobileread that others get an actual file size here.

That's for older firmware versions < 14622.

---

Are you sure the patch installed correctly? The Kobo should have rebooted after ejecting it.

**Comment by fromhz** [comment]
Hello, I'm pretty sure. Here is the log file from kobopatch_4.21.15015. After I dragged the .tgz to Kobo and ejected, it did reboot.

There is no reboot after using dictutil. I rebooted manually after seeing the error.

Is there any other information I can provide?

Thanks!

[log.txt](https://github.com/geek1011/dictutil/files/4775745/log.txt)

**Comment by geek1011** [comment]
That sounds normal. I don't think there's a problem with installation then. Can you email me the dictionaries themselves so I can take a look?

**Comment by fromhz** [comment]
Hi, so I figured out that I zipped the dictionary file at the wrong level :(
Now I get the error "No definition found. Try another dictionary."
I probably converted the dictionary wrong and it is not related to dictutil. Therefore, I'm closing the issue.
Thanks!

**Comment by geek1011** [comment]
> Hi, so I figured out that I zipped the dictionary file at the wrong level :(

Have you considered using `dicutil pack` instead of doing it manually? And, if you're making the dictionary, have you considered using `dictgen`?

**Comment by fromhz** [comment]
Hi,

Good advice, I didn't know `dictutil pack`. The html files I had were already gzipped, while `dictutil pack` takes ungzipped files.

No, I was just converting from stardict to kobo dictionary. I first used pyglossary but it gave the error. I just tried penelope and it worked!

Thanks!

**Comment by geek1011** [comment]
Speaking of penelope, if your dictionary uses accents, spaces, or cyrillic characters you'll probably want to recompile the converted dictionary by using `dictzip-decompile` and `dictgen` to have full functionality.

**Comment by fromhz** [comment]
Hi,

Thanks for the tip haha. I considered converting a French dictionary but I figured I might just stick to the default one.

Btw, if you happen to have tips for Chinese dictionary conversion, please let me know :)
